version: "3.4"
services:
    front:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                - REACT_APP_API=http://localhost:5000
        ports:
            - "8080:80"