export const ADD_MASTER='ADD_MASTER'
export const ADD_MASTER_SUCCESS='ADD_MASTER_SUCCESS'
export const ADD_MASTER_ERROR='ADD_MASTER_ERROR'

export const GET_MASTER='GET_MASTER'
export const GET_MASTER_SUCCESS='GET_MASTER_SUCCESS'
export const GET_MASTER_ERROR='GET_MASTER_ERROR'

export const DELETE_MASTER = 'DELETE_MASTER';
export const DELETE_MASTER_SUCCESS = 'DELETE_MASTER_SUCCESS';
export const DELETE_MASTER_ERROR = 'DELETE_MASTER_ERROR';


export const SET_ACTUAL_MASTER = 'SET_ACTUAL_MASTER';

export const EDIT_MASTER= 'EDIT_MASTER';
export const EDIT_MASTER_SUCCESS= 'EDIT_MASTER_SUCCESS';
export const EDIT_MASTER_ERROR= 'EDIT_MASTER_ERROR';

export const SHOW_ALERT='SHOW_ALERT'
export const HIDE_ALERT='HIDE_ALERT'

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT = 'LOGOUT';


export const GET_MASTER_STATUS = 'GET_MASTER_STATUS';
export const GET_MASTER_STATUS_SUCCESS = 'GET_MASTER_STATUS_SUCCESS';
export const GET_MASTER_STATUS_ERROR = 'GET_MASTER_STATUS_ERROR';

export const ADD_MASTER_STATUS = 'ADD_MASTER_STATUS';
export const ADD_MASTER_STATUS_SUCCESS = 'ADD_MASTER_STATUS_SUCCESS';
export const ADD_MASTER_STATUS_ERROR = 'ADD_MASTER_STATUS_ERROR';

export const GET_MASTER_STATUS_BY_ID = 'GET_MASTER_STATUS_BY_ID';
export const GET_MASTER_STATUS_BY_ID_SUCCESS = 'GET_MASTER_STATUS_BY_ID_SUCCESS';
export const GET_MASTER_STATUS_BY_ID_ERROR = 'GET_MASTER_STATUS_BY_ID_ERROR';

export const SET_ACTUAL_MASTER_STATUS = 'SET_ACTUAL_MASTER_STATUS';

export const EDIT_MASTER_STATUS= 'EDIT_MASTER_STATUS';
export const EDIT_MASTER_STATUS_SUCCESS= 'EDIT_MASTER_STATUS_SUCCESS';
export const EDIT_MASTER_STATUS_ERROR= 'EDIT_MASTER_STATUS_ERROR';

export const DELETE_MASTER_STATUS = 'DELETE_MASTER_STATUS';
export const DELETE_MASTER_STATUS_SUCCESS = 'DELETE_MASTER_STATUS_SUCCESS';
export const DELETE_MASTER_STATUS_ERROR = 'DELETE_MASTER_STATUS_ERROR';

export const FILTER_MASTER_STATUS = 'FILTER_MASTER_STATUS';
export const FILTER_MASTER = 'FILTER_MASTER';
export const FILTER_MASTER_DETAIL = 'FILTER_MASTER_DETAIL';


export const GET_MASTER_DETAIL = 'GET_MASTER_DETAIL';
export const GET_MASTER_DETAIL_SUCCESS = 'GET_MASTER_DETAIL_SUCCESS';
export const GET_MASTER_DETAIL_ERROR = 'GET_MASTER_DETAIL_ERROR';

export const ADD_MASTER_DETAIL = 'ADD_MASTER_DETAIL';
export const ADD_MASTER_DETAIL_SUCCESS = 'ADD_MASTER_DETAIL_SUCCESS';
export const ADD_MASTER_DETAIL_ERROR = 'ADD_MASTER_DETAIL_ERROR';

export const GET_MASTER_DETAIL_BY_ID = 'GET_MASTER_DETAIL_BY_ID';
export const GET_MASTER_DETAIL_BY_ID_SUCCESS = 'GET_MASTER_DETAIL_BY_ID_SUCCESS';
export const GET_MASTER_DETAIL_BY_ID_ERROR = 'GET_MASTER_DETAIL_BY_ID_ERROR';

export const SET_ACTUAL_MASTER_DETAIL = 'SET_ACTUAL_MASTER_DETAIL';

export const EDIT_MASTER_DETAIL= 'EDIT_MASTER_DETAIL';
export const EDIT_MASTER_DETAIL_SUCCESS= 'EDIT_MASTER_DETAIL_SUCCESS';
export const EDIT_MASTER_DETAIL_ERROR= 'EDIT_MASTER_DETAIL_ERROR';

export const DELETE_MASTER_DETAIL = 'DELETE_MASTER_DETAIL';
export const DELETE_MASTER_DETAIL_SUCCESS = 'DELETE_MASTER_DETAIL_SUCCESS';
export const DELETE_MASTER_DETAIL_ERROR = 'DELETE_MASTER_DETAIL_ERROR';

export const LOADING = 'LOADING';