export const ADD_MASTER='ADD_MASTER'
export const ADD_MASTER_SUCCESS='ADD_MASTER_SUCCESS'
export const ADD_MASTER_ERROR='ADD_MASTER_ERROR'

export const GET_MASTER='GET_MASTER'
export const GET_MASTER_SUCCESS='GET_MASTER_SUCCESS'
export const GET_MASTER_ERROR='GET_MASTER_ERROR'

export const GET_MASTER_DELETE='GET_MASTER_DELETE'
export const MASTER_DELETE_SUCCESS='MASTER_DELETE_SUCCESS'
export const MASTER_DELETE_ERROR='MASTER_DELETE_ERROR'

export const GET_MASTER_EDIT='GET_MASTER_EDIT'
export const START_MASTER_EDIT='START_MASTER_EDIT'
export const MASTER_EDIT_SUCCESS='MASTER_EDIT_SUCCESS'
export const MASTER_EDIT_ERROR='MASTER_EDIT_ERROR'

export const SHOW_ALERT='SHOW_ALERT'
export const HIDE_ALERT='HIDE_ALERT'

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT = 'LOGOUT';

export const LOADING = 'LOADING';